In [38]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import re
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import PorterStemmer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [41]:
df = pd.read_csv('/content/tripadvisor_hotel_reviews.csv')
conditions = [
    (df['Rating'] <= 2),
    (df['Rating'] ==3),
    (df['Rating'] > 3) 
    ]

# create a list of the values we want to assign for each condition
values = [0,1,2]

# create a new column and use np.select to assign values to it using our lists as arguments
df['Rating_numeric'] = np.select(conditions, values)
df['Review'] = df['Review'].str.lower()
#df['Review']=re.sub('[^a-z]+', ' ', df['Review'])
df = df.replace(to_replace ='[^a-z]', value = ' ', regex = True)
df['Review']=df['Review'].str.replace("  "," ")

stop = stopwords.words('english')
df['Review_without_stopwords'] = df['Review'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df['Review_tokenized'] = df.apply(lambda row: nltk.word_tokenize(row["Review_without_stopwords"]), axis=1)
ps = PorterStemmer()
df['Review_stemmed'] = df['Review_tokenized'].apply(lambda x: [ps.stem(y) for y in x])
df['Review']= df['Review_stemmed'].str.join(" ")
df

                                                  Review  ...                                     Review_stemmed
0      nice hotel expens park got good deal stay hote...  ...  [nice, hotel, expens, park, got, good, deal, s...
1      ok noth special charg diamond member hilton de...  ...  [ok, noth, special, charg, diamond, member, hi...
2      nice room experi hotel monaco seattl good hote...  ...  [nice, room, experi, hotel, monaco, seattl, go...
3      uniqu great stay wonder time hotel monaco loca...  ...  [uniqu, great, stay, wonder, time, hotel, mona...
4      great stay great stay went seahawk game awesom...  ...  [great, stay, great, stay, went, seahawk, game...
...                                                  ...  ...                                                ...
20486  best kept secret rd time stay charm star ca n ...  ...  [best, kept, secret, rd, time, stay, charm, st...
20487  great locat price view hotel great quick place...  ...  [great, locat, price, view, hotel, great, quic...
20488  ok look nice modern outsid desk staff n partic...  ...  [ok, look, nice, modern, outsid, desk, staff, ...
20489  hotel theft ruin vacat hotel open sept guest w...  ...  [hotel, theft, ruin, vacat, hotel, open, sept,...
20490  peopl talk ca n believ excel rate hotel n ye p...  ...  [peopl, talk, ca, n, believ, excel, rate, hote...

[20491 rows x 6 columns]